### ISSUE TITLE
Typo in parts list?

### ISSUE THREAD

**Issue by carlkesselman** [raspibotics/MABEL#2]
Hi,

I think there may be a type in the parts list: PCA9865 -> PCA9685?

It's a bit confusing as it seems you have changed from the Picon Zero to this alternative, which I assume will still be controlled from the Pi, not the Arduino?

Carl

**Comment by raspibotics** [comment]
Hi,
I've recently switched over to the PCA9865 servo controller on the pi as it's cheaper and more suited to my robot application, although a Piconzero is still a valid servo controller for the Pi.

**Comment by raspibotics** [comment]
Updated parts list with (PiconZero could, and previously was used)
